# Generated by Django 5.1.7 on 2025-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfeedback',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
