# Generated by Django 5.1.7 on 2025-05-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_studenttestattempt_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='testfeedback',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testfeedback',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='testfeedback',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='testfeedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='testfeedback',
            name='test',
        ),
        migrations.AddField(
            model_name='testfeedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testfeedback',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testfeedback',
            name='teacher_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testfeedback',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
